[FIXME] Revert "bsp: u-boot-ti-staging: remove duplicated deploy files"
ERROR: u-boot-ti-staging-1_2024.04+git-r0 do_deploy: ExecutionError('/srv/oe/build/tmp-lmp/work/am62xx_evm-lmp-linux/u-boot-ti-staging/2024.04+git/temp/run.do_deploy.313819', 1, None, None)
ERROR: Logfile of failure stored in: /srv/oe/build/tmp-lmp/work/am62xx_evm-lmp-linux/u-boot-ti-staging/2024.04+git/temp/log.do_deploy.313819
Log data follows:
| DEBUG: Executing python function sstate_task_prefunc
| DEBUG: Python function sstate_task_prefunc finished
| DEBUG: Executing shell function do_deploy
| rm: cannot remove '/srv/oe/build/tmp-lmp/work/am62xx_evm-lmp-linux/u-boot-ti-staging/2024.04+git/deploy-u-boot-ti-staging/u-boot-ti-staging-config-evm': No such file or directory
| WARNING: exit code 1 from a shell command.
(2024-10-01 17:48:48,031) INFO: recipe u-boot-ti-staging-1_2024.04+git-r0: task do_deploy: Failed
ERROR: Task (/srv/oe/build/conf/../../layers/meta-ti/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging_2024.04.bb:do_deploy) failed with exit code '1'

https://ci.foundries.io/projects/lmp/builds/2679/am62xx-evm/artifacts/console.log

This reverts commit c697c7f7973917117adbb8842dae0c8d11c47f44.

Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>